name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  IMAGE: sample-app-flask

jobs:
  setup-build-login-publish:
    name: Setup, Build, Login, Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$REGISTRY:$IMAGE.$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .


    # Login to docker hub
    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


    # Push the Docker image to Container Registry
    - name: Publish
      run: |-
        docker push "$REGISTRY/$IMAGE:$GITHUB_SHA"

